// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SuperPrecios.Infrastructure.EF;

#nullable disable

namespace SuperPrecios.Infrastructure.Migrations
{
    [DbContext(typeof(SuperPreciosDbContext))]
    partial class SuperPreciosDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SuperPrecios.AuthenticationCore.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");

                    b.HasDiscriminator().HasValue("Usuario");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("SuperPrecios.Domain.Entities.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("PadreId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Nombre");

                    b.HasIndex("PadreId");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("SuperPrecios.Domain.Entities.Marca", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Marcas");
                });

            modelBuilder.Entity("SuperPrecios.Domain.Entities.PrecioHistorico", b =>
                {
                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.Property<int>("SupermercadoId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<decimal>("Precio")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ProductoId", "SupermercadoId", "Fecha");

                    b.HasIndex("Fecha")
                        .HasDatabaseName("IX_PrecioHistorico_Fecha");

                    b.HasIndex("SupermercadoId")
                        .HasDatabaseName("IX_PrecioHistorico_SupermercadoId");

                    b.HasIndex("ProductoId", "SupermercadoId", "Fecha")
                        .HasDatabaseName("IX_PrecioHistorico_ProductoSupermercadoFecha");

                    b.ToTable("PreciosHistoricos");
                });

            modelBuilder.Entity("SuperPrecios.Domain.Entities.Producto", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("ImgUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("MarcaId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId")
                        .HasDatabaseName("IX_Producto_CategoriaId");

                    b.HasIndex("MarcaId")
                        .HasDatabaseName("IX_Producto_MarcaId");

                    b.HasIndex("Nombre", "MarcaId")
                        .IsUnique()
                        .HasDatabaseName("IX_Producto_NombreMarca");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("SuperPrecios.Domain.Entities.Supermercado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("WebsiteUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Supermercados");
                });

            modelBuilder.Entity("SuperPrecios.AuthenticationCore.Entities.Administrador", b =>
                {
                    b.HasBaseType("SuperPrecios.AuthenticationCore.Entities.Usuario");

                    b.HasDiscriminator().HasValue("Administrador");
                });

            modelBuilder.Entity("SuperPrecios.AuthenticationCore.Entities.Miembro", b =>
                {
                    b.HasBaseType("SuperPrecios.AuthenticationCore.Entities.Usuario");

                    b.HasDiscriminator().HasValue("Miembro");
                });

            modelBuilder.Entity("SuperPrecios.Domain.Entities.Proveedor", b =>
                {
                    b.HasBaseType("SuperPrecios.AuthenticationCore.Entities.Usuario");

                    b.Property<int?>("SupermercadoId")
                        .HasColumnType("int");

                    b.HasIndex("SupermercadoId")
                        .IsUnique()
                        .HasFilter("[SupermercadoId] IS NOT NULL");

                    b.HasDiscriminator().HasValue("Proveedor");
                });

            modelBuilder.Entity("SuperPrecios.Domain.Entities.Categoria", b =>
                {
                    b.HasOne("SuperPrecios.Domain.Entities.Categoria", "Padre")
                        .WithMany("Hijos")
                        .HasForeignKey("PadreId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Padre");
                });

            modelBuilder.Entity("SuperPrecios.Domain.Entities.PrecioHistorico", b =>
                {
                    b.HasOne("SuperPrecios.Domain.Entities.Producto", "Producto")
                        .WithMany("PreciosHistoricos")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SuperPrecios.Domain.Entities.Supermercado", "Supermercado")
                        .WithMany()
                        .HasForeignKey("SupermercadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("Supermercado");
                });

            modelBuilder.Entity("SuperPrecios.Domain.Entities.Producto", b =>
                {
                    b.HasOne("SuperPrecios.Domain.Entities.Categoria", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SuperPrecios.Domain.Entities.Marca", "Marca")
                        .WithMany("Productos")
                        .HasForeignKey("MarcaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Marca");
                });

            modelBuilder.Entity("SuperPrecios.Domain.Entities.Proveedor", b =>
                {
                    b.HasOne("SuperPrecios.Domain.Entities.Supermercado", "Supermercado")
                        .WithOne("Proveedor")
                        .HasForeignKey("SuperPrecios.Domain.Entities.Proveedor", "SupermercadoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Supermercado");
                });

            modelBuilder.Entity("SuperPrecios.Domain.Entities.Categoria", b =>
                {
                    b.Navigation("Hijos");

                    b.Navigation("Productos");
                });

            modelBuilder.Entity("SuperPrecios.Domain.Entities.Marca", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("SuperPrecios.Domain.Entities.Producto", b =>
                {
                    b.Navigation("PreciosHistoricos");
                });

            modelBuilder.Entity("SuperPrecios.Domain.Entities.Supermercado", b =>
                {
                    b.Navigation("Proveedor");
                });
#pragma warning restore 612, 618
        }
    }
}
