use SuperPrecios;
GO

INSERT INTO Usuarios VALUES ('Admin', '', 'admin@admin.com', '$2a$12$Mpocyh6Qtixvpa9nbJgWG.ZSIHWd.r844f5KGuz9yh92VaekuOAIm', 'Administrador', NULL)
GO

INSERT INTO Supermercados (Nombre, WebsiteUrl) VALUES
	('Devoto', 'https://www.devoto.com.uy'),
	('Geant', 'https://www.geant.com.uy'),
	('Disco', 'https://www.disco.com.uy'),
	('Tienda Inglesa', 'https://www.tiendainglesa.com.uy')
GO

SET IDENTITY_INSERT Categorias ON;
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (1, 'Almacén', NULL);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (2, 'Desayuno', 1);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (3, 'Café', 2);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (4, 'Cereales', 2);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (5, 'Cocoa', 2);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (6, 'Dulce de leche', 2);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (7, 'Mermeladas y dulces', 2);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (8, 'Té', 2);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (9, 'Yerbas', 2);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (10, 'Galletitas dulces', 2);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (11, 'Galletitas saladas', 2);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (12, 'Repostería', 2);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (13, 'Azúcar y edulcorantes', 2);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (14, 'Leche en polvo', 2);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (15, 'Aceites y aderezos', 1);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (16, 'Aceites', 15);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (17, 'Vinagres', 15);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (18, 'Mayonesa', 15);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (19, 'Mostaza', 15);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (20, 'Ketchup', 15);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (21, 'Salsas especiales', 15);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (22, 'Sal', 15);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (23, 'Saborizadores', 15);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (24, 'Otros condimentos', 15);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (25, 'Golosinas y chocolates', 1);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (26, 'Alfajores', 25);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (27, 'Barritas', 25);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (28, 'Bocaditos y bombones', 25);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (29, 'Caramelos, chupetines y gomitas', 25);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (30, 'Chicles', 25);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (31, 'Pastillas', 25);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (32, 'Tabletas de chocolate', 25);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (33, 'Turrones', 25);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (34, 'Popcorn', 25);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (35, 'Panificados', 1);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (36, 'Tortillas y rapiditas', 35);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (37, 'Pan de molde', 35);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (38, 'Pan tortuga y viena', 35);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (39, 'Budines y pan dulce', 35);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (40, 'Tostadas', 35);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (41, 'Pan rallado', 35);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (42, 'Snacks', 1);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (43, 'Frutos secos', 42);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (44, 'Papas fritas', 42);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (45, 'Maní', 42);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (46, 'Palitos', 42);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (47, 'Otros Snacks', 42);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (48, 'Aceitunas y encurtidos', 1);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (49, 'Aceitunas', 48);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (50, 'Encurtidos', 48);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (51, 'Conservas', 1);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (52, 'Conservas de verdura y legumbres', 51);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (53, 'Conserva de pescado', 51);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (54, 'Conserva de carne', 51);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (55, 'Conserva de fruta', 51);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (56, 'Arroz, harina y legumbres', 1);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (57, 'Arroz', 56);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (58, 'Harina y polenta', 56);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (59, 'Legumbres', 56);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (60, 'Sopas, caldos y puré', 1);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (61, 'Sopas', 60);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (62, 'Caldos', 60);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (63, 'Puré', 60);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (64, 'Pastas y salsas', 1);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (65, 'Pastas', 64);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (66, 'Salsas', 64);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (67, 'Apto para celíacos y diabéticos', 1);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (68, 'Apto para celíacos', 67);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (69, 'Apto para diabéticos', 67);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (70, 'Cigarros', 1);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (71, 'Frescos', NULL);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (72, 'Lácteos', 71);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (73, 'Huevos', 72);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (74, 'Leches', 72);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (75, 'Mantecas y margarinas', 72);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (76, 'Crema de leche', 72);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (77, 'Levaduras y grasas', 72);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (78, 'Postres', 72);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (79, 'Quesos untables', 72);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (80, 'Yogures', 72);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (81, 'Pastas y masas', 71);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (82, 'Masas de tarta', 81);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (83, 'Masas de empanada', 81);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (84, 'Pastas rellenas', 81);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (85, 'Pastas simples', 81);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (86, 'Carnicería', 71);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (87, 'Atados y carbón', 86);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (88, 'Carne vacuna', 86);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (89, 'Carne de cerdo', 86);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (90, 'Pollo', 86);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (91, 'Embutidos y achuras', 86);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (92, 'Fiambrería', 71);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (93, 'Fiambres y embutidos', 92);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (94, 'Frankfurters', 92);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (95, 'Quesos especiales', 92);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (96, 'Quesos', 92);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (97, 'Queso rallado', 92);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (98, 'Frutas y verduras', 71);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (99, 'Frutas', 98);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (100, 'Verduras', 98);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (101, 'Rotisería', 71);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (102, 'Pizza', 101);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (103, 'Sandwiches y tartas', 101);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (104, 'Otros', 101);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (105, 'Panadería', 71);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (106, 'Congelados', NULL);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (107, 'Pasta', 106);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (108, 'Vegetales', 106);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (109, 'Helados y postres', 106);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (110, 'Helados', 109);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (111, 'Postres', 109);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (112, 'Hamburguesas y Milanesas', 106);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (113, 'Hamburguesas', 112);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (114, 'Milanesas', 112);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (115, 'Pescados', 106);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (116, 'Comidas congeladas', 106);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (117, 'Guarniciones', 116);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (118, 'Pizza', 116);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (119, 'Pollo', 116);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (120, 'Otras comidas congeladas', 116);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (121, 'Empanadas y tartas', 116);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (122, 'Papas', 116);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (123, 'Hielos', 106);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (124, 'Frutas', 106);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (125, 'Bebidas', NULL);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (126, 'Aguas', 125);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (127, 'Aguas con gas', 126);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (128, 'Aguas sin gas', 126);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (129, 'Aguas saborizadas', 126);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (130, 'Cerveza', 125);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (131, 'Jugos', 125);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (132, 'En polvo', 131);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (133, 'Jugos liquidos', 131);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (134, 'Gaseosas', 125);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (135, 'Vinos y espumantes', 125);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (136, 'Vinos de mesa', 135);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (137, 'Vinos finos', 135);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (138, 'Espumantes', 135);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (139, 'Energizantes e isotónicas', 125);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (140, 'Whiskys, bebidas blancas y aperitivos', 125);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (141, 'Whiskys', 140);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (142, 'Bebidas blancas', 140);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (143, 'Aperitivos', 140);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (144, 'Perfumería', NULL);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (145, 'Cuidado del cabello', 144);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (146, 'Shampoo', 145);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (147, 'Acondicionador', 145);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (148, 'Tratamiento capilar', 145);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (149, 'Tintas', 145);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (150, 'Fijadores', 145);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (151, 'Accesorios para el cabello', 145);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (152, 'Cuidado oral', 144);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (153, 'Cremas dentales', 152);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (154, 'Cepillos dentales', 152);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (155, 'Enjuague bucal y accesorios', 152);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (156, 'Cuidado facial', 144);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (157, 'Cremas faciales', 156);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (158, 'Maquillaje y accesorios', 156);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (159, 'Afeitado', 156);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (160, 'Cuidado corporal', 144);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (161, 'Jabones', 160);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (162, 'Desodorantes', 160);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (163, 'Cremas corporales', 160);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (164, 'Manos y pies', 160);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (165, 'Perfumes y fragancias', 160);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (166, 'Depilación', 160);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (167, 'Talcos', 160);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (168, 'Protectores solares', 144);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (169, 'Cuidado del adulto', 144);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (170, 'Incontinencia', 169);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (171, 'Protección feminina', 144);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (172, 'Toallas femeninas', 171);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (173, 'Protectores diarios', 171);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (174, 'Tampones', 171);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (175, 'Otros perfumería', 144);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (176, 'Otros', 175);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (177, 'Alcohol', 175);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (178, 'Algodones', 175);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (179, 'Hisopos', 175);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (180, 'Esponjas', 175);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (181, 'Curitas', 175);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (182, 'Preservativos', 175);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (183, 'Bolsas de agua caliente', 175);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (184, 'Tapabocas', 175);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (185, 'Limpieza', NULL);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (186, 'Desodorante de ambiente', 185);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (187, 'Limpieza de baños y cocina', 185);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (188, 'Detergentes', 187);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (189, 'Lavavajillas', 187);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (190, 'Limpiadores de cocina', 187);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (191, 'Limpiadores de baño', 187);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (192, 'Limpiadores cremosos', 187);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (193, 'Limpiadores específicos', 187);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (194, 'Lavandina', 187);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (195, 'Limpieza pisos y muebles', 185);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (196, 'Limpiadores de piso', 195);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (197, 'Limpia muebles', 195);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (198, 'Ceras y autobrillos', 195);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (199, 'Limpieza de ropa', 185);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (200, 'Jabón liquido', 199);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (201, 'Jabón en polvo', 199);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (202, 'Jabón en barra', 199);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (203, 'Suavizantes', 199);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (204, 'Prelavados y quitamanchas', 199);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (205, 'Perfume para tela', 199);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (206, 'Papeles', 185);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (207, 'Papel higiénico', 206);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (208, 'Rollos de cocina', 206);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (209, 'Servilletas', 206);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (210, 'Pañuelos', 206);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (211, 'Insecticidas, plaguicidas y repelentes', 185);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (212, 'Insecticidas', 211);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (213, 'Repelentes', 211);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (214, 'Otros', 211);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (215, 'Accesorios de limpieza', 185);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (216, 'Guantes esponjas y paños', 215);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (217, 'Escobas mopas y cepillos', 215);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (218, 'Baldes y palanganas', 215);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (219, 'Cestos', 215);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (220, 'Fósforos y encendedores', 215);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (221, 'Bolsas residuos', 215);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (222, 'Otros accesorios', 215);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (223, 'Otros limpiadores', 185);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (224, 'Autos', 223);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (225, 'Calzado', 223);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (226, 'Bebés', NULL);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (227, 'Cuidado del bebé', 226);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (228, 'Pañales', 227);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (229, 'Toallitas húmedas', 227);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (230, 'Shampoo, jabones y otros', 227);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (231, 'Alimentación Infantil', 226);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (232, 'Puericultura', 226);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (233, 'Ferreteria', NULL);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (234, 'Herramientas', 233);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (235, 'Manuales', 234);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (236, 'Eléctricas', 234);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (237, 'Lamparitas y electricidad', 233);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (238, 'Lámparas led', 237);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (239, 'Linternas', 237);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (240, 'Materiales eléctricos', 233);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (241, 'Fichas y adaptadores', 240);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (242, 'Alargues', 240);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (243, 'Pilas y accesorios', 233);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (244, 'Pilas', 243);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (245, 'Accesorios', 243);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (246, 'Adhesivos y otros', 233);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (247, 'Adhesivos', 246);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (248, 'Otros', 246);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (249, 'Mascotas', NULL);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (250, 'Alimento para gato', 249);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (251, 'Alimento para perro', 249);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (252, 'Accesorios', 249);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (253, 'Textil', NULL);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (254, 'Ropa niños', 253);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (255, 'Pantalones y jeans', 254);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (256, 'Ropa de abrigo', 254);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (257, 'Remeras y blusas', 254);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (258, 'Calzado', 254);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (259, 'Malla y shorts de baño', 254);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (260, 'Ropa interior y medias', 254);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (261, 'Túnicas delantales y moñas', 254);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (262, 'Ropa damas', 253);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (263, 'Ropa interior', 262);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (264, 'Remeras y camisas', 262);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (265, 'Pantalones y jeans', 262);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (266, 'Ropa de verano', 262);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (267, 'Ropa de abrigo', 262);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (268, 'Calzado', 262);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (269, 'Mallas', 262);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (270, 'Ropa hombres', 253);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (271, 'Ropa interior', 270);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (272, 'Remeras y camisas', 270);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (273, 'Short de baño', 270);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (274, 'Pantalones, jeans y short', 270);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (275, 'Ropa de abrigo', 270);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (276, 'Calzado', 270);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (277, 'Ropa bebés', 253);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (278, 'Accesorios', 253);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (279, 'Juguetería y librería', NULL);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (280, 'Jugueteria', 279);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (281, 'Juegos de rol', 280);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (282, 'Muñecas y accesorios', 280);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (283, 'Deporte y aire libre', 280);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (284, 'Figuras y animales', 280);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (285, 'Manualidades y accesorios', 280);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (286, 'Primera infancia', 280);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (287, 'Didáctico', 280);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (288, 'Licencias', 280);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (289, 'Vehículos y pistas', 280);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (290, 'Piscinas, inflables y accesorios', 280);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (291, 'Librería', 279);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (292, 'Cartuchera', 291);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (293, 'Encuadernados', 291);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (294, 'Mochilas', 291);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (295, 'Útiles', 291);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (296, 'Uniformes escolares', 291);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (297, 'Hogar y bazar', NULL);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (298, 'Navidad', 297);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (299, 'Textil hogar', 297);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (300, 'Mates, termos y bombillas', 297);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (301, 'Decoración', 297);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (302, 'Relojes, espejos y porta-retratos', 301);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (303, 'Velas y aromaterapia', 301);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (304, 'Varios decoración', 301);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (305, 'Plásticos y descartables', 297);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (306, 'Plásticos', 305);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (307, 'Descartables', 305);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (308, 'Bolsas reutilizables', 305);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (309, 'Cotillón', 297);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (310, 'Velas cumpleaños', 309);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (311, 'Globos', 309);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (312, 'Varios', 309);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (313, 'Aire libre', 297);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (314, 'Sillas y mesas', 313);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (315, 'Carpas, gazebos y otros', 313);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (316, 'Colchones y sobres de dormir', 313);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (317, 'Conservadores', 313);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (318, 'Deportes y fitness', 297);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (319, 'Artículos de mesa', 297);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (320, 'Vajilla', 319);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (321, 'Cubiertos', 319);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (322, 'Bowls y recipientes', 319);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (323, 'Complementos de mesa', 319);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (324, 'Botellas y vasos para llevar', 319);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (325, 'Cristalería', 297);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (326, 'Vasos y copas', 325);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (327, 'Jarras', 325);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (328, 'Cocina', 297);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (329, 'Tablas', 328);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (330, 'Asaderas y fuentes', 328);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (331, 'Cacerolas y sartenes', 328);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (332, 'Utensilios para cocinar', 328);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (333, 'Utensilios para servir', 328);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (334, 'Almacenamiento de alimentos', 328);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (335, 'Escurridores', 328);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (336, 'Calderas', 328);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (337, 'Organización', 297);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (338, 'Cajas, canastos y otros', 337);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (339, 'Cestos y recipientes para residuos', 337);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (340, 'Organización de ropa', 337);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (341, 'Accesorios de baño', 297);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (342, 'Belleza y cuidado personal ', NULL);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (343, 'Artefactos para el Cabello', 342);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (344, 'Bucleras', 343);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (345, 'Cepillos eléctricos', 343);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (346, 'Cortadoras de Pelo', 343);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (347, 'Planchitas', 343);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (348, 'Secadores de Pelo', 343);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (349, 'Trimmers', 343);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (350, 'Barbería', 342);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (351, 'Afeitadoras', 350);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (352, 'Depilación', 342);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (353, 'Depiladoras', 352);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (354, 'Tratamientos de Belleza', 342);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (355, 'Otros', 354);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (356, 'Celulares y Telefonía', NULL);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (357, 'Accesorios para Celulares', 356);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (358, 'Cables de Datos', 357);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (359, 'Otros', 357);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (360, 'Cargadores', 357);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (361, 'Celulares y Smartphones', 356);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (362, 'Smartwatches y Accesorios', 356);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (363, 'Smartwatches', 362);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (364, 'Telefonía Fija e Inalámbrica', 356);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (365, 'Teléfonos', 364);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (366, 'Computación', NULL);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (367, 'Almacenamiento', 366);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (368, 'Pen Drives', 367);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (369, 'Cables y Hubs USB', 366);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (370, 'Conectividad y Redes', 366);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (371, 'Routers', 370);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (372, 'Impresión', 366);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (373, 'Impresoras', 372);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (374, 'Laptops y Accesorios', 366);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (375, 'Notebooks', 374);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (376, 'Monitores y Accesorios', 366);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (377, 'Monitores', 376);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (378, 'Otros', 376);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (379, 'Periféricos de PC', 366);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (380, 'Mouses y Teclados', 379);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (381, 'Tablets y Accesorios', 366);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (382, 'Consolas y Videojuegos', NULL);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (383, 'Accesorios para PC Gaming', 382);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (384, 'Auriculares', 383);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (385, 'Controles para Gamers', 383);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (386, 'Micrófonos', 383);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (387, 'Consolas', 382);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (388, 'Deportes y Fitness', NULL);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (389, 'Ciclismo', 388);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (390, 'Bicicletas', 389);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (391, 'Bicicletas Fijas', 389);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (392, 'Fitness y Musculación', 388);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (393, 'Aparatos de Musculación', 392);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (394, 'Funcional, Pilates y Yoga', 392);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (395, 'Máquinas Cardiovasculares', 392);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (396, 'Pesas, discos y barras', 392);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (397, 'Electrodomésticos y Aires Ac.', NULL);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (398, 'Climatización', 397);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (399, 'Aires Acondicionados', 398);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (400, 'Estufas y Calefactores', 398);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (401, 'Otros', 398);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (402, 'Termotanques y Calefones', 398);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (403, 'Ventiladores', 398);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (404, 'Cocción', 397);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (405, 'Anafes', 404);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (406, 'Cocinas', 404);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (407, 'Extractores y Purificadores', 404);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (408, 'Hornos', 404);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (409, 'Kits de Anafes y Extractores', 404);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (410, 'Microondas', 404);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (411, 'Lavado', 397);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (412, 'Lavarropas y Lavasecarropas', 411);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (413, 'Lavavajillas', 411);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (414, 'Secarropas', 411);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (415, 'Pequeños Electrodomésticos', 397);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (416, 'Otros', 415);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (417, 'Para Cocina', 415);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (418, 'Para Hogar', 415);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (419, 'Refrigeración', 397);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (420, 'Cavas para Vinos', 419);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (421, 'Freezers', 419);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (422, 'Frigobares', 419);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (423, 'Heladeras', 419);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (424, 'Electrónica, Audio y Video', NULL);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (425, 'Audio', 424);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (426, 'Auriculares', 425);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (427, 'Parlantes, Bafles y Subwoofers', 425);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (428, 'Radios AM/FM', 425);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (429, 'Torres de Sonido', 425);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (430, 'Cables', 424);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (431, 'Otros Cables', 430);
INSERT INTO Categorias (Id, Nombre, PadreId) VALUES (432, 'Televisores', 424);
SET IDENTITY_INSERT Categorias OFF;