name: Build and Deploy ASP.NET Core app - superprecios

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Show repo structure (debug)
        run: ls -R

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0'

      - name: Build app
        run: dotnet build SuperPrecios.Web/SuperPrecios.Web.csproj --configuration Release

      - name: Publish app
        run: dotnet publish SuperPrecios.Web/SuperPrecios.Web.csproj -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_024F0D65D3154002BB0891039514E05B }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_423B4E0F4A22407DBCC128ADDD13F8FF }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_A9AFC8691DDB43818B376A706E5B7AD2 }}

      - name: Setup .NET for EF Tools
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0'

      - name: Install dotnet-ef tool
        run: dotnet tool install --global dotnet-ef

      - name: Apply EF Core migrations
        env:
          ConnectionStrings__ConexionBD: ${{ secrets.PROD_CONNECTION_STRING }}
        run: |
          export PATH="$PATH:/home/runner/.dotnet/tools"
          dotnet ef database update --project SuperPrecios.Infrastructure/SuperPrecios.Infrastructure.csproj --startup-project SuperPrecios.Web/SuperPrecios.Web.csproj --context SuperPreciosDbContext

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'superprecios'
          slot-name: 'Production'
          package: ${{ env.DOTNET_ROOT }}/myapp
